# Generated by Django 4.2.30 on 2026-06-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='preferred_movement',
            field=models.CharField(max_length=200, verbose_name='Предпочитано движение'),
        ),
    ]
