# Generated by Django 4.2.30 on 2026-07-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_preferred_movement_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='Съгласие за обработка на лични данни'),
        ),
    ]
