# Generated by Django 4.2.30 on 2026-07-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_questionnaireresponse_consent_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Име'),
        ),
        migrations.CreateModel(
            name='StepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='Категория')),
                ('step_text', models.TextField(verbose_name='Стъпка')),
                ('completed_on', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_completions', to='plans.questionnaireresponse')),
            ],
            options={
                'verbose_name': 'Изпълнена стъпка',
                'verbose_name_plural': 'Изпълнени стъпки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['response', 'completed_on'], name='plans_stepc_respons_b38201_idx')],
            },
        ),
    ]
