# Generated by Django 4.2.30 on 2026-07-15 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0004_questionnaireresponse_first_name_stepcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL, verbose_name='Потребител'),
        ),
    ]
