# Generated by Django 4.2.30 on 2026-07-18 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_configure_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[('core_habit', 'Основен навик'), ('growth_mission', 'Мисия за растеж')], default='core_habit', max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('why', models.TextField(blank=True)),
                ('verification_type', models.CharField(choices=[('sensor', 'Сензор'), ('timer', 'Таймер'), ('location', 'Локация'), ('photo_ai', 'Снимка/AI'), ('confirm', 'Потвърждение')], default='confirm', max_length=20)),
                ('verification_source', models.CharField(blank=True, max_length=64)),
                ('metric', models.CharField(blank=True, max_length=32)),
                ('level_scaling', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Ниво')),
                ('min_days', models.PositiveSmallIntegerField(default=14, verbose_name='Минимум дни')),
                ('consistency_req', models.PositiveSmallIntegerField(verbose_name='Постоянство %')),
                ('completion_req', models.PositiveSmallIntegerField(verbose_name='Завършеност %')),
                ('core_habit_req', models.PositiveSmallIntegerField(verbose_name='Основни навици %')),
            ],
            options={
                'verbose_name': 'Ниво',
                'verbose_name_plural': 'Нива',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('level_started_on', models.DateField(auto_now_add=True)),
                ('extended_days', models.PositiveSmallIntegerField(default=0)),
                ('recovery_until', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='plans.questionnaireresponse')),
            ],
            options={
                'verbose_name': 'Програма на потребител',
                'verbose_name_plural': 'Програми на потребители',
            },
        ),
        migrations.CreateModel(
            name='TreeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0)),
                ('growth_stage', models.PositiveSmallIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('health', models.PositiveSmallIntegerField(default=100)),
                ('branches', models.PositiveIntegerField(default=0)),
                ('leaves', models.PositiveIntegerField(default=0)),
                ('flowers', models.PositiveIntegerField(default=0)),
                ('dormant', models.BooleanField(default=False)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tree_state', to='plans.questionnaireresponse')),
            ],
            options={
                'verbose_name': 'Състояние на дървото',
                'verbose_name_plural': 'Състояния на дърветата',
            },
        ),
        migrations.CreateModel(
            name='HabitStability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('stability', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_stabilities', to='plans.questionnaireresponse')),
            ],
            options={
                'verbose_name': 'Стабилност на навик',
                'verbose_name_plural': 'Стабилности на навици',
                'unique_together': {('response', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DailyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('core', 'Основен навик'), ('mission', 'Мисия')], default='core', max_length=10)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.actiondef')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='plans.questionnaireresponse')),
            ],
            options={
                'verbose_name': 'Дневно назначение',
                'verbose_name_plural': 'Дневни назначения',
                'indexes': [models.Index(fields=['response', 'date'], name='plans_daily_respons_c2370f_idx')],
                'unique_together': {('response', 'date', 'action')},
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Изчаква'), ('verified', 'Потвърдено (сензор)'), ('unverified', 'Непотвърдено'), ('confirmed', 'Потвърдено (доверие)'), ('rejected', 'Отхвърлено')], default='pending', max_length=20)),
                ('verification_type', models.CharField(blank=True, max_length=20)),
                ('claimed_value', models.FloatField(blank=True, null=True)),
                ('measured_value', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.actiondef')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='plans.questionnaireresponse')),
            ],
            options={
                'verbose_name': 'Дневник на действие',
                'verbose_name_plural': 'Дневник на действия',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['response', 'date'], name='plans_actio_respons_5f02b6_idx')],
            },
        ),
    ]
