# Generated by Django 4.2.30 on 2026-07-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_seed_habit_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondef',
            name='alternatives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='actiondef',
            name='contraindications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='actiondef',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='actiondef',
            name='duration_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actiondef',
            name='weather_adaptations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
