# Generated by Django 4.2.30 on 2026-07-19 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_expand_action_library_to_100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='plans.questionnaireresponse')),
            ],
            options={
                'verbose_name': 'Размисъл',
                'verbose_name_plural': 'Размисли',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['response', 'date'], name='plans_refle_respons_1fb3cd_idx')],
                'unique_together': {('response', 'date')},
            },
        ),
    ]
